[tool.poetry]
name = "nba-data-drift"
version = "0.1.0"
description = ""
authors = ["j-friis <xdr476@alumni.ku.dk>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
